# Generated by Django 5.0.1 on 2024-03-25 13:42

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0003_alter_principal_user"),
    ]

    operations = [
        migrations.CreateModel(
            name="ScheduleList",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=255)),
                (
                    "schedules",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=255), size=0
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="Principal",
        ),
    ]
