# Generated by Django 5.0.1 on 2024-03-25 16:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0004_schedulelist_delete_principal"),
    ]

    operations = [
        migrations.AlterField(
            model_name="teacher",
            name="contract",
            field=models.CharField(max_length=255),
        ),
    ]
