# Generated by Django 5.0.1 on 2024-03-25 16:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0005_alter_teacher_contract"),
    ]

    operations = [
        migrations.AlterField(
            model_name="teacher",
            name="schedule",
            field=models.CharField(max_length=255),
        ),
    ]
