# Generated by Django 5.0.1 on 2024-03-25 16:33

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0006_alter_teacher_schedule"),
    ]

    operations = [
        migrations.AlterField(
            model_name="teacher",
            name="schedule",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=255), size=0
            ),
        ),
    ]
